In [20]:
import pandas as pd
data = pd.read_csv("Pokemon.csv")
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [21]:
#Compute mean of Speed and HP
speed_mean = data["Speed"].mean()
hp_mean = data["HP"].mean()
print(speed_mean)
print(hp_mean)
def set_speed(val):
    if val < speed_mean:
        return "Low_Speed"
    elif val == speed_mean:
        return "Neutral_Speed"
    else:
        return "High_Speed"
def set_hp(val):
    if val < hp_mean:
        return "Low_Hp"
    elif val == hp_mean:
        return "Neutral_Hp"
    else:
        return "High_Hp"

68.2775
69.25875

In [22]:
data["Speed_high_low"] = data["Speed"].apply(set_speed)
data["HP_high_low"] = data["HP"].apply(set_hp)
data

       #                   Name   Type 1  ... Legendary  Speed_high_low  HP_high_low
0      1              Bulbasaur    Grass  ...     False       Low_Speed       Low_Hp
1      2                Ivysaur    Grass  ...     False       Low_Speed       Low_Hp
2      3               Venusaur    Grass  ...     False      High_Speed      High_Hp
3      3  VenusaurMega Venusaur    Grass  ...     False      High_Speed      High_Hp
4      4             Charmander     Fire  ...     False       Low_Speed       Low_Hp
..   ...                    ...      ...  ...       ...             ...          ...
795  719                Diancie     Rock  ...      True       Low_Speed       Low_Hp
796  719    DiancieMega Diancie     Rock  ...      True      High_Speed       Low_Hp
797  720    HoopaHoopa Confined  Psychic  ...      True      High_Speed      High_Hp
798  720     HoopaHoopa Unbound  Psychic  ...      True      High_Speed      High_Hp
799  721              Volcanion     Fire  ...      True      High_Speed      High_Hp

[800 rows x 15 columns]